name: glancego
description: "Find everything you're looking for | An open-source file finder and application launcher designed to streamline your workflow."

publish_to: "none"
homepage: https://softyes.com.br
repository: https://github.com/GlanceGo/glancego_desktop

platforms:
  linux:
  macos:
  windows:

screenshots:
  - description: "GlanceGo project logo"
    path: readme/logo.png

version: 0.3.0+4

environment:
  sdk: ^3.8.1
  flutter: ^3.32.5

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.1
  google_fonts: ^6.2.1
  dart_mappable: ^4.5.0
  path_provider: ^2.1.5
  window_manager: ^0.5.0
  hotkey_manager: ^0.2.3
  flutter_acrylic: ^1.1.4
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.8
  solar_icon_pack: ^0.2.1
  flutter_modular: ^6.3.3
  flutter_command: ^7.2.2
  package_info_plus: ^8.3.0
  dynamic_system_colors: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  fastforge: ^0.6.0
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0
  dart_mappable_builder: ^4.5.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
