title: GlanceGo
icon: icon.icns
background: background.png
background-color: #131520
window:
  size:
    width: 600
    height: 600
contents:
  - x: 128
    y: 360
    type: file
    path: GlanceGo.app
  - x: 470
    y: 360
    type: link
    path: "/Applications"
